name: Sync with HuggingFace

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Fetch LFS objects
        run: git lfs fetch --all  # 確保所有 LFS 物件都被下載
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push -f https://HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/Skywind5487/TNFSHClassTable main
